function run_conn_pipeline(struct_file, func_file, output_dir)
% Fully automated CONN pipeline: preprocessing -> denoising -> ROI-to-ROI analysis

conn_module('clear');

output_file = fullfile(output_dir, 'conn_project01.mat');

% ====== Setup + Preprocessing ======
clear batch;
batch.filename = output_file;
batch.Setup.isnew = 1;
batch.Setup.nsubjects = 1;
batch.Setup.RT = 2.0;
batch.Setup.structurals = {struct_file};
batch.Setup.functionals = {{func_file}};
batch.Setup.preprocessing.steps = {'default_mni'};
batch.Setup.preprocessing.sliceorder = 'ascending';
batch.Setup.preprocessing.fwhm = 5;
batch.Setup.preprocessing.art_thresholds = [5 0.45 1 1 1 0 0 4];
% batch.Setup.preprocessing.removescans = 4;
batch.Setup.conditions.names = {'rest'};
batch.Setup.conditions.onsets = {{0}};
batch.Setup.conditions.durations = {{inf}};
batch.Setup.done = true;
conn_batch(batch);

% ====== Denoising ======
batch = [];
batch.filename = output_file;
batch.Denoising.filter = [0.008 0.09];
batch.Denoising.regbp = 1;
batch.Denoising.confounds.names = {'White Matter', 'CSF', 'realignment', 'scrubbing', 'Effect of rest'};
batch.Denoising.confounds.dimensions = {5, 5, inf, inf, inf};
batch.Denoising.confounds.deriv = {0, 0, 1, 0, 1};
batch.Denoising.confounds.power = {1, 1, 2, 1, 1};
batch.Denoising.done = true;
conn_batch(batch);

% ====== Analysis ======
batch = [];
batch.filename = output_file;
batch.Analysis.name = 'SBC_01';
batch.Analysis.type = 'ROI-to-ROI';
batch.Analysis.measure = 'correlation (bivariate)';
batch.Analysis.sources = { ...
    'networks.DefaultMode.MPFC', ...
    'networks.DefaultMode.LP (L)', ...
    'networks.DefaultMode.LP (R)', ...
    'networks.DefaultMode.PCC', ...
    'networks.SensoriMotor.Lateral (L)', ...
    'networks.SensoriMotor.Lateral (R)', ...
    'networks.SensoriMotor.Superior', ...
    'networks.Visual.Medial', ...
    'networks.Visual.Occipital', ...
    'networks.Visual.Lateral (L)', ...
    'networks.Visual.Lateral (R)', ...
    'networks.Salience.ACC', ...
    'networks.Salience.AInsula (L)', ...
    'networks.Salience.AInsula (R)', ...
    'networks.Salience.RPFC (L)', ...
    'networks.Salience.RPFC (R)', ...
    'networks.Salience.SMG (L)', ...
    'networks.Salience.SMG (R)', ...
    'networks.DorsalAttention.FEF (L)', ...
    'networks.DorsalAttention.FEF (R)', ...
    'networks.DorsalAttention.IPS (L)', ...
    'networks.DorsalAttention.IPS (R)', ...
    'networks.FrontoParietal.LPFC (L)', ...
    'networks.FrontoParietal.PPC (L)', ...
    'networks.FrontoParietal.LPFC (R)', ...
    'networks.FrontoParietal.PPC (R)', ...
    'networks.Language.IFG (L)', ...
    'networks.Language.IFG (R)', ...
    'networks.Language.pSTG (L)', ...
    'networks.Language.pSTG (R)', ...
    'networks.Cerebellar.Anterior', ...
    'networks.Cerebellar.Posterior' ...
};
batch.Analysis.done = true;
conn_batch(batch);

disp(['CONN pipeline completed successfully for subject: ', struct_file]);
end

